os: linux

branches:
  only:
    - main

addons:
  apt:
    packages:
      - texlive
      - doxygen

script:
  - doxygen Doxyfile
  - ls -l -a -r

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  keep_history: true
  on:
    branch: main
